apiVersion: v1
kind: Service
metadata:
  name: {{ include "gekko.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gekko.name" . }}
    helm.sh/chart: {{ include "gekko.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 80
    targetPort: http
    {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePorts.http)))}}
    nodePort: {{ .Values.service.nodePorts.http }}
    {{- end }}
  - name: https
    port: 443
    targetPort: https
    {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePorts.https)))}}
    nodePort: {{ .Values.service.nodePorts.https }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "gekko.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
