{{- if .Values.ingress.enabled -}}
{{- $fullName := include "gekko.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}-virtualservice
  labels:
    app.kubernetes.io/name: {{ include "gekko.name" . }}
    helm.sh/chart: {{ include "gekko.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.ingress.gateway.name }}
  http:
  - match:
    - uri:
        prefix: {{ $ingressPath }}
    rewrite:
      uri: " "
    route:
    - destination:
        port:
          number: 80
        host: {{ $fullName }}
{{- end }}